In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 2. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**2.1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [11]:
## your code
2**np.arange(1,21,1) / np.arange(1,21,1)

array([2.00000000e+00, 2.00000000e+00, 2.66666667e+00, 4.00000000e+00,
       6.40000000e+00, 1.06666667e+01, 1.82857143e+01, 3.20000000e+01,
       5.68888889e+01, 1.02400000e+02, 1.86181818e+02, 3.41333333e+02,
       6.30153846e+02, 1.17028571e+03, 2.18453333e+03, 4.09600000e+03,
       7.71011765e+03, 1.45635556e+04, 2.75941053e+04, 5.24288000e+04])

**2.2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [23]:
## your code
np.sum(0.1**(np.arange(0,6,1) * 3) * 0.2**(np.arange(0,6,1) * 4)) 

1.00000160000256

**2.3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [29]:
## your code
a = np.zeros((8,8))
a[1::2, 1::2] = 1
a[::2, ::2] = 1
a

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

**2.4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [56]:

X = np.random.random((5, 2))
## your code
r = np.sqrt(X[:,0]**2 + X[:,1]**2)
fi = np.arctan(X[:,1] / X[:,0])
print(np.array([r,fi]).reshape(X.shape))


[[0.7513266  0.92001808]
 [0.74354253 0.56814236]
 [0.34164211 0.42200624]
 [0.28874467 0.69279984]
 [0.31401154 0.84183645]]
[[1.18782361 0.93575704]
 [0.5429628  0.75056319]
 [0.89849422 0.8859891 ]
 [0.65246549 0.89024931]
 [1.1759092  1.21377341]]


**2.5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [77]:
X = np.random.random((10, 10))
## your code
#найдет все индексы
print(np.argwhere((X == X.max()) == True)) 
#найдет только первый встретившийся
idmax = X.argmax()
print(idmax // 10, idmax % 10)

[[1 7]]
1 7


**2.6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [99]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))
## your code
distances = np.linalg.norm(X - y, axis = 1)
print('Min point in X', X[distances.argmin()])

Min point in X [0.38181052 0.35766281]


**2.7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [186]:
## your code
x = np.linspace(-3, 3, 7)
print(x)
p1 = x[x < 0]**2 + 2 * x[x < 0] + 6
p2 = x[(x >= 0) & (x <= 2)] + 6
p3 = x[x >= 2]**2 + 4 * x[x >= 2] - 4
print(np.concatenate((p1,p2,p3), axis=0))

[-3. -2. -1.  0.  1.  2.  3.]
[ 9.  6.  5.  6.  7.  8.  8. 17.]


**2.8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [134]:
X = np.random.random((10, 10))
## your code
X = X - X.mean(axis = 1, keepdims = True)
X.mean(axis = 1)

array([-1.22124533e-16, -4.44089210e-17, -5.55111512e-17,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00, -7.77156117e-17,  2.22044605e-17,
       -1.11022302e-17,  8.32667268e-17])

**2.9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [148]:
X = np.random.normal(loc=5, scale=2., size=1000)
print(X.mean(), X.var(ddof = 0), sep = '\t')

4.9680615156663315	4.385394453864343


**2.10.** Создать матрицу (NB. БЕЗ ЦИКЛОВ И ИЗМЕНЕНИЯ ОТДЕЛЬНЫХ ЭЛЕМЕНТОВ):

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [176]:
## your code
y = np.arange(0,5).reshape(-1,1)
a = np.array([np.arange(0,5)] * 5)
print((a + y) % 5)


[[0 1 2 3 4]
 [1 2 3 4 0]
 [2 3 4 0 1]
 [3 4 0 1 2]
 [4 0 1 2 3]]


**2.11.** Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [193]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)    

[0, 0, 4, 0, 4]

Реализуйте данный алгоритм более оптимальным способом, без использования циклов.

In [198]:
## your code
def opt_sample(x, c):
    assert len(x) > 0
    indxes = np.arange(0, len(x))
    pr = x / np.sum(x)
    return np.random.choice(indxes, size = c, p = pr)

In [199]:
opt_sample([50, 3, 1, 7, 20], 5)

array([0, 3, 0, 4, 4])